--[[ 
  Generated by Lua Obfuscator (XOR + Base64 - Created By Zeraphis - https://encrypt.zeraphis.co.uk)
]]--

local _p = "MQ0GBxQRSB8mDAUMDwkBBUoGCgxGQkcDWAMGFwEOAE9MJ01FQ0gNAQQEQU0VDwkYCxUhTBkEQ1VBCx8VQh8REEYQDB86TgIXBlImCxM1QQwcBholDxMEBURvaUhBTkcMS00LDBxBHgsEVAgXJwkVD0cKX00LDBxBHgsEVAgXJwkVD0kGRBkMGQ0PBwNFWQUADWJBTkdFDU1FQwQIDEkLQhkMBRFJFW1FDU1FQ0hBTkdFDU0RChwNC0dYDUomChwIFAILDSQhRERrTkdFDU1FQ0hBTkdFSQgWABoIHhMMQgNFXkhGLQ4RRBcADUgoKkcLQhlFBQcUAANLCkFvQ0hBTkdFDU1FQ0hBGh4VSE1YQ08EHBUKX0pJaUhBTkdFDU1FQ0hBTgMQXwwRCgcPTlpFHF1VU1hBQ0pFHF1FEA0CAQkBXmdFQ0hBTkdFDRBMaUhBTkdFDU1FEQ0VGxULJ01FQ0gEAANvJ01FQ0gNBwVLQwIRCg4YRhxvDU1FQ0hBTkcRRBkJBkhcTkAmRBkMGQ0PTi4hCkFvQ0hBTkdFDU0BBhsCHA4VWQQKDUhcTk9CdAIQEUgiBxMMVwgLQyElVEdAXkpMWQ4OHAoEWUUVDwkYCxUhTBkETQsIGg4fSAMMB0FNZEdFDU1FQ0hBGh4VSE1YQ08SGwQGSB4WRERrTkdFDU1FQ0gFGxUEWQQKDUhcTlZVHV1VQ0VMTlZVDR4AAAcPChRvDU1FQxVIZAILSUFFBQkNHQJMJw=="

local __b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function __b64decode(data)
  data = data:gsub('[^'..__b64chars..'=]', '')
  return (data:gsub('.', function(x)
    if x == '=' then return '' end
    local r,f='',(__b64chars:find(x)-1)
    for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
    return r
  end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
    if #x ~= 8 then return '' end
    local c=0
    for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
    return string.char(c)
  end))
end

local function __xor(data, key)
  if not key or #key == 0 then return data end
  local out={}
  for i=1,#data do
    out[i]=string.char((data:byte(i) ~ key:byte(((i-1)%#key)+1)))
  end
  return table.concat(out)
end

local __plain = __xor(__b64decode(_p), "change-me")
local __fn = load(__plain)
return __fn()